# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f6e92c942e952d69b8e965b54afefc946ebe1ff0532c8dcc033c6431e63b65190bb17d4a7ed053707fd52a43d2752ce4f6f1069707a7dadd1eae1fda113b682

test:
  secret_key_base: b32580d4b0eabcb83dd751f4572a440171088debe5f38baa2d1796a72c431d6681c714b78d4ee166730fe0b62e994849699ceaa604cda775d3403bad99194d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
